services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GeorgRinger\Feediting\:
    resource: '../Classes/*'

  GeorgRinger\Feediting\Edit\Clipboar:
    public: true

  GeorgRinger\Feediting\ContentObject\EditableFluidTemplateContentObject:
    tags:
      - name: frontend.contentobject
        identifier: 'FLUIDTEMPLATE'